use std::{collections::BTreeMap, time::Duration};

use ros_z::{
    Builder,
    msg::{ZDeserializer, ZMessage},
    node::ZNode,
    pubsub::ZSub,
    time::ZTime,
};
use tokio::select;
use zenoh::Result as ZResult;

use crate::announce::{Announcement, WithId};

/// A future queue checks for a single topic what messages are currently in-flight.
///
/// A message on the topic `/example` is considered in-flight if an [`Announcement`] has been published on `/example/announcement`.
/// Once the message has been received in the queue, the message is no longer considered in-flight.
pub struct FutureQueueSubscriber<T>
where
    WithId<T>: ZMessage,
{
    data_subscriber: ZSub<WithId<T>>,
    announcement_subscriber: ZSub<Announcement>,
    /// The expected lag between when data is actually generated by the sensor
    /// (as indicated by the [`Announcement`] time) and when its announcement is made.
    estimated_lag: Duration,
    inflight: BTreeMap<u64, ZTime>,
}

impl<T> FutureQueueSubscriber<T>
where
    WithId<T>: ZMessage,
    for<'a> <WithId<T> as ZMessage>::Serdes:
        ZDeserializer<Input<'a> = &'a [u8], Output = WithId<T>>,
{
    /// This function returns the next message from the queue, waiting for it if necessary.
    /// Simultaneously, it returns the time for the oldest in-flight message.
    pub async fn sub_async(&mut self) -> ZResult<(ZTime, T)> {
        loop {
            // TODO(oleflb): require biased? Is ordering guaranteed?
            select! {
                result = self.announcement_subscriber.async_recv() => {
                    let announcement = result?;
                    self.inflight.insert(announcement.id, announcement.time);
                }
                result = self.data_subscriber.async_recv() => {
                    let WithId { id, value } = result?;
                    let oldest_inflight = self.inflight.first_entry().expect("no announcement yet").get().clone();
                    self.inflight.remove(&id);
                    return Ok((oldest_inflight, value))
                },
            }
        }
    }
}

pub trait CreateFutureQueue<T>
where
    WithId<T>: ZMessage,
{
    fn create_fut_sub(
        &self,
        topic: &str,
        estimated_lag: Duration,
    ) -> ZResult<FutureQueueSubscriber<T>>;
}

impl<T> CreateFutureQueue<T> for ZNode
where
    WithId<T>: ZMessage,
{
    fn create_fut_sub(
        &self,
        topic: &str,
        estimated_lag: Duration,
    ) -> ZResult<FutureQueueSubscriber<T>> {
        let data_subscriber = self.create_sub(topic).build()?;
        let announcement_subscriber = self.create_sub(&format!("{}/announce", topic)).build()?;

        Ok(FutureQueueSubscriber {
            data_subscriber,
            announcement_subscriber,
            estimated_lag,
            inflight: BTreeMap::new(),
        })
    }
}
