[package]
name = "hulk_ros_z"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true }
ros-z = { workspace = true }
ros-z-config = { workspace = true }
ros-z-msgs = { workspace = true, features = ["sensor_msgs"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zenoh = { workspace = true }
